### ISSUE TITLE
Readme File - Link topics.

### ISSUE THREAD

**Issue by ankit-sr** [GoTo-Coders/DS-Algo#16]
## 📚 Documentation

Till now, the readme file contains only the name of topics present in the folders. I suggest that those topics should be the link of the respective folder to make the transition much more easier.

**Comment by imsushant12** [comment]
The topis name is mentioned above the links so I guess it is recognizable. Also If we make seperate README for each folder of each langauge then it would become chaos.

**Comment by ankit-sr** [comment]
I am not asking to create a separate readme file for each folder.
What I'm trying to say is to generate a link for each folder.
For example :-
### [ Folder_name ](foldername\)
- [ topic name ] (foldername\topicname)

**Comment by imsushant12** [comment]
Yes, for that we have a README in main directory and there you should add the directory and file as you said.

**Comment by imsushant12** [comment]
https://github.com/GoTo-Coders/DS-Algo/blob/main/README.md
Here is the README which I am talking about
