### ISSUE TITLE
Preorder Traversal Iterative

### ISSUE THREAD

**Issue by ankit-sr** [GoTo-Coders/DS-Algo#77]
## 🚀 Feature

traversing a binary tree without using recursion i.e. via stack.

## Language 

C++

## Pitch

Code not present in the repo.

**Comment by imsushant12** [comment]
Which traversal you are talking about? Preorder/ PostOrder ??

**Comment by ankit-sr** [comment]
Preorder Traversal
I've mentioned it in the issue topic.
Even though, sorry for the inconvenience.
