### ISSUE TITLE
Breadth_First_Search(BFS)

### ISSUE THREAD

**Issue by Nilesh363** [GoTo-Coders/DS-Algo#9]
## 🚀 Feature

Breadth first search is a graph traversal algorithm that starts traversing the graph from root node and explores all the neighbouring nodes. 
Then, it selects the nearest node and explore all the unexplored nodes. 
The algorithm follows the same process for each of the nearest node until it finds the goal.

## Language 

C++

## Pitch

It is not in the list

**Comment by ankit-sr** [comment]
Submit a pull request for Readme also
