### ISSUE TITLE
Array Implementation

### ISSUE THREAD

**Issue by ankit-sr** [GoTo-Coders/DS-Algo#91]
## 🚀 Feature

An array is a linear data structure. The program is to implement all the basic operations performed on an array.

## Language 

C++

## Pitch
The program is not present in the repository.

**Comment by Amisha328** [comment]
Hey, @ankit-sr 
I have a small query, that am I supposed to make a separate file for each operation or all the operations in one single file by making different functions for each operation?

**Comment by ankit-sr** [comment]
Hi @Amisha328 
You can make a single file (for example, Array_Implementaion) that includes all the operations related to an array, such as Insertion, Updation, Deletion, Searching, etc.

**Comment by omkar619-dev** [comment]
will using stl like this do sir?

vector <int> v;
v.pushback(1);
v.pushback(2);
v.pushback(3);
v.pushback(4);
v.pushback(5);          //{1,2,3,4,5}

for(int i=0; i<v.size(); i++)
{ 
cout << v[i] << endl;

}

**Comment by Amisha328** [comment]
> Hi @Amisha328
> You can make a single file (for example, Array_Implementaion) that includes all the operations related to an array, such as Insertion, Updation, Deletion, Searching, etc.

Thanks a lot. I will do it ASAP.👍

**Comment by imsushant12** [comment]
> will using stl like this do sir?
> 
> vector v;
> v.pushback(1);
> v.pushback(2);
> v.pushback(3);
> v.pushback(4);
> v.pushback(5); //{1,2,3,4,5}
> 
> for(int i=0; i<v.size(); i++)
> {
> cout << v[i] << endl;
> 
> }

Hey Omkar, actually the program is to visualise the operations of array so stl will not be helpful here. 
Also,we have assigned this issue to @Amisha328 so, I would suggest you to raise issues on different topics as we have a lot to consider.

**Comment by omkar619-dev** [comment]
> > will using stl like this do sir?
> > vector v;
> > v.pushback(1);
> > v.pushback(2);
> > v.pushback(3);
> > v.pushback(4);
> > v.pushback(5); //{1,2,3,4,5}
> > for(int i=0; i<v.size(); i++)
> > {
> > cout << v[i] << endl;
> > }
> 
> Hey Omkar, actually the program is to visualise the operations of array so stl will not be helpful here.
> Also,we have assigned this issue to @Amisha328 so, I would suggest you to raise issues on different topics as we have a lot to consider.

Ohh Okay,thank you for clarifying though!
